import { VolunteerServiceRecord, InstructionRecord, GratificationRecord, UserProfile, CalendarTask } from '../types';

export const DEFAULT_GRATIFICATION_RATES: Record<string, number> = {
  'DECIR': 84.00,
  'DECIR 1/2': 42.00,
  'BAL': 65.00,
  'Subida de Categoria': 120.00,
  'Prevenção': 50.00,
  'DIPIR': 75.00,
  'Outra Gratificação': 50.00,
};

export const initialUserProfile: UserProfile = {
  name: 'Bombeiro Voluntário',
  firefighterNumber: '',
  corpsName: 'Corpo de Bombeiros',
  rank: 'Bombeiro de 3ª Classe',
  monthlyTargetHours: 35,
  pinEnabled: false,
  pinHash: '',
  theme: 'dark',
  showReminder: true,
  googleUser: null,
  gratificationRates: DEFAULT_GRATIFICATION_RATES,
  autoEmailReportEnabled: false,
  autoEmailAddress: '',
  autoEmailTime: '20:00',
  autoEmailReportPeriod: 'monthly',
};

export const initialVolunteerRecords: VolunteerServiceRecord[] = [
  {
    id: 'vol-1',
    date: '2026-08-28',
    startTime: '08:00',
    endTime: '16:30',
    durationMinutes: 510,
    serviceType: 'Incêndio Rural',
    incidentNumber: '2026/0891',
    vehicle: 'VFCI 02',
    location: 'Serra de Sintra - Encosta Norte',
    notes: 'Apoio no combate a foco de reacendimento florestal. Vigilância e rescaldo.',
    createdAt: Date.now() - 3 * 86400000,
  },
  {
    id: 'vol-2',
    date: '2026-08-25',
    startTime: '19:00',
    endTime: '23:30',
    durationMinutes: 270,
    serviceType: 'Piquete/Socorro',
    incidentNumber: '2026/0874',
    vehicle: 'ABSC 04',
    location: 'Quartel Central',
    notes: 'Piquete noturno de socorro pré-hospitalar.',
    createdAt: Date.now() - 6 * 86400000,
  },
  {
    id: 'vol-3',
    date: '2026-08-20',
    startTime: '09:00',
    endTime: '13:00',
    durationMinutes: 240,
    serviceType: 'Acidente',
    incidentNumber: '2026/0832',
    vehicle: 'VTGC 01 / ABSC 01',
    location: 'IC19 - Nó de Queluz',
    notes: 'Desencarceramento e socorro em colisão rodoviária.',
    createdAt: Date.now() - 11 * 86400000,
  },
  {
    id: 'vol-4',
    date: '2026-08-14',
    startTime: '14:00',
    endTime: '22:00',
    durationMinutes: 480,
    serviceType: 'Incêndio Urbano',
    incidentNumber: '2026/0812',
    vehicle: 'VLCI 01',
    location: 'Zona Industrial de Alfragide',
    notes: 'Incêndio em armazém e ventilação tática.',
    createdAt: Date.now() - 17 * 86400000,
  },
  {
    id: 'vol-5',
    date: '2026-08-05',
    startTime: '08:00',
    endTime: '20:00',
    durationMinutes: 720,
    serviceType: 'Incêndio Rural',
    incidentNumber: '2026/0788',
    vehicle: 'VFCI 01',
    location: 'Reforço DECIR Nível III',
    notes: 'Apoio em Teatro de Operações Florestal.',
    createdAt: Date.now() - 26 * 86400000,
  },
  {
    id: 'vol-prev-months',
    date: '2026-07-20',
    startTime: '08:00',
    endTime: '20:00',
    durationMinutes: 20400, // Total accumulated hours in 2026 (summing to ~377h total)
    serviceType: 'Piquete/Socorro',
    incidentNumber: '2026/DECIR-TOTAL',
    vehicle: 'VFCI / ABSC',
    location: 'Serviços acumulados de Janeiro a Julho 2026',
    notes: 'Total de piquetes, ocorrências de socorro e manobras do primeiro semestre.',
    createdAt: Date.now() - 40 * 86400000,
  },
];

export const initialInstructionRecords: InstructionRecord[] = [
  {
    id: 'inst-1',
    date: '2026-08-30',
    startTime: '09:00',
    endTime: '14:00',
    durationMinutes: 300, // 5 hours
    topic: 'Registo Nacional RCP',
    instructor: 'Chefe X',
    entity: 'Escola Nacional de Bombeiros / INEM',
    location: 'Centro de Formação Operacional',
    notes: 'Protocolos atualizados de Reanimação Cardiopulmonar e Suporte Básico de Vida com DAE.',
    certificateRef: 'RCP-2026-NAC/089',
    createdAt: Date.now() - 1 * 86400000,
  },
  {
    id: 'inst-2',
    date: '2026-08-24',
    startTime: '18:00',
    endTime: '22:00',
    durationMinutes: 240, // 4 hours
    topic: 'Salvamento e Desencarceramento (SD)',
    instructor: 'Chefe António Martins',
    entity: 'Corpo de Bombeiros',
    location: 'Parque de Treino de Manobras',
    notes: 'Técnicas de corte e estabilização rápida de veículos pesados.',
    certificateRef: 'CB-SD-2026/24',
    createdAt: Date.now() - 7 * 86400000,
  },
  {
    id: 'inst-3',
    date: '2026-08-10',
    startTime: '08:30',
    endTime: '13:30',
    durationMinutes: 300, // 5 hours
    topic: 'Combate a Incêndios Florestais (CIF)',
    instructor: 'Comandante Pedro Sousa',
    entity: 'ENB (Escola Nacional de Bombeiros)',
    location: 'Pólo Regional',
    notes: 'Módulo de segurança e progressão de equipas de ataque.',
    certificateRef: 'ENB-CIF-2026/102',
    createdAt: Date.now() - 21 * 86400000,
  },
  {
    id: 'inst-prev-months',
    date: '2026-06-15',
    startTime: '09:00',
    endTime: '18:00',
    durationMinutes: 1920, // Accumulated instruction hours in 2026 (summing to exactly 46h = 2760 mins)
    topic: 'Formação Modular e Recertificações Semestrais',
    instructor: 'Chefe X',
    entity: 'Escola Nacional de Bombeiros',
    location: 'Quartel e Centro Técnico',
    notes: 'Módulos semestrais de SIRESP, TAT, Matérias Perigosas e Condução TT.',
    createdAt: Date.now() - 75 * 86400000,
  },
];

export const initialGratificationRecords: GratificationRecord[] = [
  {
    id: 'grat-1',
    date: '2026-08-30',
    type: 'DECIR',
    amount: 840.00, // 10 dias DECIR @ 84€
    receiptNumber: 'DECIR-AGO-26/19',
    paidStatus: 'Pendente',
    notes: '10 Diárias de reforço no dispositivo especial DECIR 2026.',
    createdAt: Date.now() - 1 * 86400000,
  },
  {
    id: 'grat-2',
    date: '2026-08-25',
    type: 'BAL',
    amount: 195.00, // 3 diárias BAL @ 65€
    receiptNumber: 'BAL-AGO-2026/04',
    paidStatus: 'Pendente',
    notes: 'Brigada Autónoma de Linha / Apoio Operacional.',
    createdAt: Date.now() - 6 * 86400000,
  },
  {
    id: 'grat-3',
    date: '2026-08-16',
    type: 'Prevenção',
    amount: 150.00,
    receiptNumber: 'PREV-2026/044',
    paidStatus: 'Recebido',
    paymentDate: '2026-08-20',
    notes: 'Serviço de prevenção operacional em evento público.',
    createdAt: Date.now() - 15 * 86400000,
  },
  {
    id: 'grat-4',
    date: '2026-08-10',
    type: 'DIPIR',
    amount: 150.00,
    receiptNumber: 'DIPIR-2026/012',
    paidStatus: 'Recebido',
    paymentDate: '2026-08-15',
    notes: 'Dispositivo Integrado Permanente de Intervenção Rápida.',
    createdAt: Date.now() - 21 * 86400000,
  },
  {
    id: 'grat-5',
    date: '2026-08-02',
    type: 'DECIR 1/2',
    amount: 42.00,
    receiptNumber: 'DECIR-MEIA-2026/01',
    paidStatus: 'Recebido',
    paymentDate: '2026-08-05',
    notes: 'Meia diária DECIR.',
    createdAt: Date.now() - 29 * 86400000,
  },
];

export const initialCalendarTasks: CalendarTask[] = [
  {
    id: 'task-1',
    title: 'Piquete Noturno 20h-08h',
    date: '2026-08-31',
    time: '20:00',
    type: 'Piquete / Turno',
    priority: 'Alta',
    completed: false,
    location: 'Quartel Central',
    notes: 'Piquete de socorro em ambulância ABSC 02.',
    createdAt: Date.now() - 86400000,
  },
  {
    id: 'task-2',
    title: 'Verificação de Material de Desencarceramento',
    date: '2026-08-30',
    time: '17:30',
    type: 'Tarefa Operacional',
    priority: 'Média',
    completed: true,
    location: 'Oficina / Parque Viaturas',
    notes: 'Testar motobombas hidráulicas e tesouras Lukas.',
    createdAt: Date.now() - 2 * 86400000,
  },
  {
    id: 'task-3',
    title: 'Módulo de Recertificação TAT / SBV',
    date: '2026-09-05',
    time: '09:00',
    type: 'Formação',
    priority: 'Alta',
    completed: false,
    location: 'Sala de Formação ENB',
    notes: 'Trazer fardamento de instrução e manual.',
    createdAt: Date.now() - 3 * 86400000,
  },
  {
    id: 'task-4',
    title: 'Escala DECIR Nível II',
    date: '2026-09-08',
    time: '08:00',
    type: 'Escala de Serviço',
    priority: 'Alta',
    completed: false,
    location: 'Posto de Vigia / Quartel',
    notes: 'Reforço para aviso meteorológico amarelo.',
    createdAt: Date.now() - 4 * 86400000,
  },
];

